
// This file has been generated by the GUI designer. Do not modify.
namespace SymlinkMaker.GUI.GTKSharp
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action Action;
		
		private global::Gtk.VBox vboxBase;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label lblSourcePath;
		
		private global::Gtk.Entry txtBoxSource;
		
		private global::Gtk.Image imgSourcePath;
		
		private global::Gtk.Button btnFindSource;
		
		private global::Gtk.Button btnOpenSource;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label lblTargetPath;
		
		private global::Gtk.Entry txtBoxTarget;
		
		private global::Gtk.Image imgTargetPath;
		
		private global::Gtk.Button btnFindTarget;
		
		private global::Gtk.Button btnOpenTarget;
		
		private global::Gtk.HSeparator hseparator2;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Button btnDoWhole;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Button btnCopySource;
		
		private global::Gtk.Button btnDeleteSource;
		
		private global::Gtk.Button btnCreateSymlink;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SymlinkMaker.GUI.GTKSharp.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.Action = new global::Gtk.Action ("Action", null, null, null);
			w1.Add (this.Action, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "SymlinkMaker.GUI.GTKSharp.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Symlink Maker");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-last", global::Gtk.IconSize.LargeToolbar);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SymlinkMaker.GUI.GTKSharp.MainWindow.Gtk.Container+ContainerChild
			this.vboxBase = new global::Gtk.VBox ();
			this.vboxBase.Name = "vboxBase";
			this.vboxBase.Spacing = 6;
			this.vboxBase.BorderWidth = ((uint)(6));
			// Container child vboxBase.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblSourcePath = new global::Gtk.Label ();
			this.lblSourcePath.Name = "lblSourcePath";
			this.lblSourcePath.LabelProp = global::Mono.Unix.Catalog.GetString ("Source path");
			this.hbox1.Add (this.lblSourcePath);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblSourcePath]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtBoxSource = new global::Gtk.Entry ();
			this.txtBoxSource.CanFocus = true;
			this.txtBoxSource.Name = "txtBoxSource";
			this.txtBoxSource.IsEditable = true;
			this.txtBoxSource.InvisibleChar = '●';
			this.hbox1.Add (this.txtBoxSource);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtBoxSource]));
			w3.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.imgSourcePath = new global::Gtk.Image ();
			this.imgSourcePath.Name = "imgSourcePath";
			this.imgSourcePath.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.hbox1.Add (this.imgSourcePath);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.imgSourcePath]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnFindSource = new global::Gtk.Button ();
			this.btnFindSource.CanFocus = true;
			this.btnFindSource.Name = "btnFindSource";
			this.btnFindSource.UseUnderline = true;
			this.btnFindSource.Label = global::Mono.Unix.Catalog.GetString ("Find");
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save-as", global::Gtk.IconSize.Menu);
			this.btnFindSource.Image = w5;
			this.hbox1.Add (this.btnFindSource);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnFindSource]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnOpenSource = new global::Gtk.Button ();
			this.btnOpenSource.CanFocus = true;
			this.btnOpenSource.Name = "btnOpenSource";
			this.btnOpenSource.UseStock = true;
			this.btnOpenSource.UseUnderline = true;
			this.btnOpenSource.Label = "gtk-open";
			this.hbox1.Add (this.btnOpenSource);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnOpenSource]));
			w7.Position = 4;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblTargetPath = new global::Gtk.Label ();
			this.lblTargetPath.Name = "lblTargetPath";
			this.lblTargetPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Target path");
			this.hbox2.Add (this.lblTargetPath);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblTargetPath]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.txtBoxTarget = new global::Gtk.Entry ();
			this.txtBoxTarget.CanFocus = true;
			this.txtBoxTarget.Name = "txtBoxTarget";
			this.txtBoxTarget.IsEditable = true;
			this.txtBoxTarget.InvisibleChar = '●';
			this.hbox2.Add (this.txtBoxTarget);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtBoxTarget]));
			w10.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.imgTargetPath = new global::Gtk.Image ();
			this.imgTargetPath.Name = "imgTargetPath";
			this.imgTargetPath.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.hbox2.Add (this.imgTargetPath);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.imgTargetPath]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnFindTarget = new global::Gtk.Button ();
			this.btnFindTarget.CanFocus = true;
			this.btnFindTarget.Name = "btnFindTarget";
			this.btnFindTarget.UseUnderline = true;
			this.btnFindTarget.Label = global::Mono.Unix.Catalog.GetString ("Find");
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save-as", global::Gtk.IconSize.Menu);
			this.btnFindTarget.Image = w12;
			this.hbox2.Add (this.btnFindTarget);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnFindTarget]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnOpenTarget = new global::Gtk.Button ();
			this.btnOpenTarget.CanFocus = true;
			this.btnOpenTarget.Name = "btnOpenTarget";
			this.btnOpenTarget.UseStock = true;
			this.btnOpenTarget.UseUnderline = true;
			this.btnOpenTarget.Label = "gtk-open";
			this.hbox2.Add (this.btnOpenTarget);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnOpenTarget]));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vboxBase.Add (this.vbox3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vboxBase [this.vbox3]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vboxBase.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vboxBase.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxBase [this.hseparator2]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vboxBase.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vboxBase.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vboxBase [this.hseparator1]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vboxBase.Gtk.Box+BoxChild
			this.btnDoWhole = new global::Gtk.Button ();
			this.btnDoWhole.CanFocus = true;
			this.btnDoWhole.Name = "btnDoWhole";
			this.btnDoWhole.UseUnderline = true;
			this.btnDoWhole.Label = global::Mono.Unix.Catalog.GetString ("Launch complete process");
			this.vboxBase.Add (this.btnDoWhole);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vboxBase [this.btnDoWhole]));
			w19.PackType = ((global::Gtk.PackType)(1));
			w19.Position = 4;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vboxBase.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnCopySource = new global::Gtk.Button ();
			this.btnCopySource.CanFocus = true;
			this.btnCopySource.Name = "btnCopySource";
			this.btnCopySource.UseUnderline = true;
			this.btnCopySource.Label = global::Mono.Unix.Catalog.GetString ("Copy the source directory");
			this.hbox3.Add (this.btnCopySource);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnCopySource]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnDeleteSource = new global::Gtk.Button ();
			this.btnDeleteSource.CanFocus = true;
			this.btnDeleteSource.Name = "btnDeleteSource";
			this.btnDeleteSource.UseUnderline = true;
			this.btnDeleteSource.Label = global::Mono.Unix.Catalog.GetString ("Delete the source directory");
			this.hbox3.Add (this.btnDeleteSource);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnDeleteSource]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnCreateSymlink = new global::Gtk.Button ();
			this.btnCreateSymlink.CanFocus = true;
			this.btnCreateSymlink.Name = "btnCreateSymlink";
			this.btnCreateSymlink.UseUnderline = true;
			this.btnCreateSymlink.Label = global::Mono.Unix.Catalog.GetString ("Create the symbolic link");
			this.hbox3.Add (this.btnCreateSymlink);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnCreateSymlink]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.vboxBase.Add (this.hbox3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vboxBase [this.hbox3]));
			w23.PackType = ((global::Gtk.PackType)(1));
			w23.Position = 5;
			w23.Expand = false;
			w23.Fill = false;
			this.Add (this.vboxBase);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 569;
			this.DefaultHeight = 202;
			this.Show ();
		}
	}
}
