
// This file has been generated by the GUI designer. Do not modify.
namespace SymlinkMaker.GUI.GtkSharp
{
	public partial class MainWindowView
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action openAction;
		
		private global::Gtk.Action SettingsAction;
		
		private global::Gtk.ToggleAction toggleRequireConfirmAction;
		
		private global::Gtk.Action FileAction;
		
		private global::Gtk.Action HelpAction;
		
		private global::Gtk.Action aboutAction;
		
		private global::Gtk.Action EditAction;
		
		private global::Gtk.Action copyAction;
		
		private global::Gtk.Action cutAction;
		
		private global::Gtk.Action pasteAction;
		
		private global::Gtk.Action undoAction;
		
		private global::Gtk.Action redoAction;
		
		private global::Gtk.Action undoAction1;
		
		private global::Gtk.Action redoAction1;
		
		private global::Gtk.Action redoAction2;
		
		private global::Gtk.VBox vboxBase;
		
		private global::Gtk.MenuBar menubar;
		
		private global::Gtk.VBox vboxContent;
		
		private global::Gtk.HBox hboxHeader;
		
		private global::Gtk.Label labelSource;
		
		private global::Gtk.Label labelTarget;
		
		private global::Gtk.HBox hboxMiddle;
		
		private global::Gtk.Button btnFindSource;
		
		private global::Gtk.Entry txtBoxSource;
		
		private global::Gtk.Image imgSourcePath;
		
		private global::Gtk.Arrow arrowPaths;
		
		private global::Gtk.Image imgTargetPath;
		
		private global::Gtk.Button btnFindTarget;
		
		private global::Gtk.Entry txtBoxTarget;
		
		private global::Gtk.HBox hboxBottom;
		
		private global::Gtk.VBox vboxSource;
		
		private global::Gtk.HBox hboxSourceButtons;
		
		private global::Gtk.Button btnOpenSource;
		
		private global::Gtk.Button btnDeleteSource;
		
		private global::Gtk.VBox vboxButtons;
		
		private global::Gtk.Button btnMoveSource;
		
		private global::Gtk.Button btnCopySource;
		
		private global::Gtk.Button btnCreateSymlink;
		
		private global::Gtk.Button btnDoWhole;
		
		private global::Gtk.VBox vboxTarget;
		
		private global::Gtk.HBox hboxTargetButtons;
		
		private global::Gtk.Button btnDeleteTarget;
		
		private global::Gtk.Button btnOpenTarget;
		
		private global::Gtk.HSeparator hseparator1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SymlinkMaker.GUI.GtkSharp.MainWindowView
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
			w1.Add (this.openAction, null);
			this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
			this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
			w1.Add (this.SettingsAction, null);
			this.toggleRequireConfirmAction = new global::Gtk.ToggleAction ("toggleRequireConfirmAction", global::Mono.Unix.Catalog.GetString ("Always ask before running a command"), global::Mono.Unix.Catalog.GetString ("lways ask before running a command"), "gtk-dialog-question");
			this.toggleRequireConfirmAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Require confirmation");
			w1.Add (this.toggleRequireConfirmAction, null);
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
			w1.Add (this.HelpAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.aboutAction, null);
			this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
			w1.Add (this.EditAction, null);
			this.copyAction = new global::Gtk.Action ("copyAction", global::Mono.Unix.Catalog.GetString ("_Copy"), null, "gtk-copy");
			this.copyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Copy");
			w1.Add (this.copyAction, null);
			this.cutAction = new global::Gtk.Action ("cutAction", global::Mono.Unix.Catalog.GetString ("Cu_t"), null, "gtk-cut");
			this.cutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cu_t");
			w1.Add (this.cutAction, null);
			this.pasteAction = new global::Gtk.Action ("pasteAction", global::Mono.Unix.Catalog.GetString ("_Paste"), null, "gtk-paste");
			this.pasteAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Paste");
			w1.Add (this.pasteAction, null);
			this.undoAction = new global::Gtk.Action ("undoAction", global::Mono.Unix.Catalog.GetString ("_Undo"), null, "gtk-undo");
			this.undoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Undo");
			w1.Add (this.undoAction, null);
			this.redoAction = new global::Gtk.Action ("redoAction", null, null, "gtk-redo");
			w1.Add (this.redoAction, null);
			this.undoAction1 = new global::Gtk.Action ("undoAction1", global::Mono.Unix.Catalog.GetString ("_Undo"), null, "gtk-undo");
			this.undoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Undo");
			w1.Add (this.undoAction1, null);
			this.redoAction1 = new global::Gtk.Action ("redoAction1", global::Mono.Unix.Catalog.GetString ("_Redo"), null, "gtk-redo");
			this.redoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Redo");
			w1.Add (this.redoAction1, null);
			this.redoAction2 = new global::Gtk.Action ("redoAction2", global::Mono.Unix.Catalog.GetString ("_Redo"), null, "gtk-redo");
			this.redoAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Redo");
			w1.Add (this.redoAction2, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "SymlinkMaker.GUI.GtkSharp.MainWindowView";
			this.Title = global::Mono.Unix.Catalog.GetString ("Symlink Maker");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-last", global::Gtk.IconSize.LargeToolbar);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SymlinkMaker.GUI.GtkSharp.MainWindowView.Gtk.Container+ContainerChild
			this.vboxBase = new global::Gtk.VBox ();
			this.vboxBase.Name = "vboxBase";
			this.vboxBase.Spacing = 6;
			// Container child vboxBase.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar'><menu name='FileAction' action='FileAction'/><menu name='EditAction' action='EditAction'><menuitem name='copyAction' action='copyAction'/><menuitem name='cutAction' action='cutAction'/><menuitem name='pasteAction' action='pasteAction'/><menuitem name='undoAction1' action='undoAction1'/><menuitem name='redoAction2' action='redoAction2'/></menu><menu name='SettingsAction' action='SettingsAction'><menuitem name='toggleRequireConfirmAction' action='toggleRequireConfirmAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
			this.menubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar")));
			this.menubar.Name = "menubar";
			this.vboxBase.Add (this.menubar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxBase [this.menubar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxBase.Gtk.Box+BoxChild
			this.vboxContent = new global::Gtk.VBox ();
			this.vboxContent.Name = "vboxContent";
			this.vboxContent.Spacing = 6;
			this.vboxContent.BorderWidth = ((uint)(5));
			// Container child vboxContent.Gtk.Box+BoxChild
			this.hboxHeader = new global::Gtk.HBox ();
			this.hboxHeader.Name = "hboxHeader";
			this.hboxHeader.Spacing = 6;
			// Container child hboxHeader.Gtk.Box+BoxChild
			this.labelSource = new global::Gtk.Label ();
			this.labelSource.Name = "labelSource";
			this.labelSource.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Source directory</b>");
			this.labelSource.UseMarkup = true;
			this.hboxHeader.Add (this.labelSource);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hboxHeader [this.labelSource]));
			w3.Position = 0;
			w3.Padding = ((uint)(9));
			// Container child hboxHeader.Gtk.Box+BoxChild
			this.labelTarget = new global::Gtk.Label ();
			this.labelTarget.Name = "labelTarget";
			this.labelTarget.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Target directory</b>");
			this.labelTarget.UseMarkup = true;
			this.hboxHeader.Add (this.labelTarget);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hboxHeader [this.labelTarget]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 2;
			w4.Padding = ((uint)(8));
			this.vboxContent.Add (this.hboxHeader);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxContent [this.hboxHeader]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vboxContent.Gtk.Box+BoxChild
			this.hboxMiddle = new global::Gtk.HBox ();
			this.hboxMiddle.Name = "hboxMiddle";
			this.hboxMiddle.Spacing = 6;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.btnFindSource = new global::Gtk.Button ();
			this.btnFindSource.TooltipMarkup = "Find the source directory";
			this.btnFindSource.CanFocus = true;
			this.btnFindSource.Name = "btnFindSource";
			this.btnFindSource.UseUnderline = true;
			this.btnFindSource.Label = global::Mono.Unix.Catalog.GetString ("...");
			this.hboxMiddle.Add (this.btnFindSource);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle [this.btnFindSource]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.txtBoxSource = new global::Gtk.Entry ();
			this.txtBoxSource.CanFocus = true;
			this.txtBoxSource.Name = "txtBoxSource";
			this.txtBoxSource.IsEditable = true;
			this.txtBoxSource.InvisibleChar = '●';
			this.hboxMiddle.Add (this.txtBoxSource);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle [this.txtBoxSource]));
			w7.Position = 1;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.imgSourcePath = new global::Gtk.Image ();
			this.imgSourcePath.Name = "imgSourcePath";
			this.imgSourcePath.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-yes", global::Gtk.IconSize.Menu);
			this.hboxMiddle.Add (this.imgSourcePath);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle [this.imgSourcePath]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.arrowPaths = new global::Gtk.Arrow (((global::Gtk.ArrowType)(3)), ((global::Gtk.ShadowType)(4)));
			this.arrowPaths.Name = "arrowPaths";
			this.hboxMiddle.Add (this.arrowPaths);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle [this.arrowPaths]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.imgTargetPath = new global::Gtk.Image ();
			this.imgTargetPath.Name = "imgTargetPath";
			this.imgTargetPath.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-yes", global::Gtk.IconSize.Menu);
			this.hboxMiddle.Add (this.imgTargetPath);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle [this.imgTargetPath]));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.btnFindTarget = new global::Gtk.Button ();
			this.btnFindTarget.TooltipMarkup = "Find the target directory";
			this.btnFindTarget.CanFocus = true;
			this.btnFindTarget.Name = "btnFindTarget";
			this.btnFindTarget.UseUnderline = true;
			this.btnFindTarget.Label = global::Mono.Unix.Catalog.GetString ("...");
			this.hboxMiddle.Add (this.btnFindTarget);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle [this.btnFindTarget]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 5;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hboxMiddle.Gtk.Box+BoxChild
			this.txtBoxTarget = new global::Gtk.Entry ();
			this.txtBoxTarget.CanFocus = true;
			this.txtBoxTarget.Name = "txtBoxTarget";
			this.txtBoxTarget.IsEditable = true;
			this.txtBoxTarget.InvisibleChar = '●';
			this.hboxMiddle.Add (this.txtBoxTarget);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxMiddle [this.txtBoxTarget]));
			w12.PackType = ((global::Gtk.PackType)(1));
			w12.Position = 6;
			this.vboxContent.Add (this.hboxMiddle);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxContent [this.hboxMiddle]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vboxContent.Gtk.Box+BoxChild
			this.hboxBottom = new global::Gtk.HBox ();
			this.hboxBottom.Name = "hboxBottom";
			this.hboxBottom.Spacing = 6;
			// Container child hboxBottom.Gtk.Box+BoxChild
			this.vboxSource = new global::Gtk.VBox ();
			this.vboxSource.Name = "vboxSource";
			this.vboxSource.Spacing = 6;
			// Container child vboxSource.Gtk.Box+BoxChild
			this.hboxSourceButtons = new global::Gtk.HBox ();
			this.hboxSourceButtons.Name = "hboxSourceButtons";
			this.hboxSourceButtons.Spacing = 6;
			// Container child hboxSourceButtons.Gtk.Box+BoxChild
			this.btnOpenSource = new global::Gtk.Button ();
			this.btnOpenSource.TooltipMarkup = "Open the source directory with the File Explorer ";
			this.btnOpenSource.CanFocus = true;
			this.btnOpenSource.Name = "btnOpenSource";
			this.btnOpenSource.UseStock = true;
			this.btnOpenSource.UseUnderline = true;
			this.btnOpenSource.Label = "gtk-open";
			this.hboxSourceButtons.Add (this.btnOpenSource);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hboxSourceButtons [this.btnOpenSource]));
			w14.Position = 0;
			// Container child hboxSourceButtons.Gtk.Box+BoxChild
			this.btnDeleteSource = new global::Gtk.Button ();
			this.btnDeleteSource.TooltipMarkup = "Delete the source directory";
			this.btnDeleteSource.CanFocus = true;
			this.btnDeleteSource.Name = "btnDeleteSource";
			this.btnDeleteSource.UseStock = true;
			this.btnDeleteSource.UseUnderline = true;
			this.btnDeleteSource.Label = "gtk-delete";
			this.hboxSourceButtons.Add (this.btnDeleteSource);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hboxSourceButtons [this.btnDeleteSource]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vboxSource.Add (this.hboxSourceButtons);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vboxSource [this.hboxSourceButtons]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			this.hboxBottom.Add (this.vboxSource);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hboxBottom [this.vboxSource]));
			w17.Position = 0;
			// Container child hboxBottom.Gtk.Box+BoxChild
			this.vboxButtons = new global::Gtk.VBox ();
			this.vboxButtons.Name = "vboxButtons";
			this.vboxButtons.Spacing = 6;
			// Container child vboxButtons.Gtk.Box+BoxChild
			this.btnMoveSource = new global::Gtk.Button ();
			this.btnMoveSource.TooltipMarkup = "Move the source directory to the target location";
			this.btnMoveSource.CanFocus = true;
			this.btnMoveSource.Name = "btnMoveSource";
			this.btnMoveSource.UseUnderline = true;
			this.btnMoveSource.Label = "Move to";
			global::Gtk.Image w18 = new global::Gtk.Image ();
			w18.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-jump-to", global::Gtk.IconSize.Menu);
			this.btnMoveSource.Image = w18;
			this.vboxButtons.Add (this.btnMoveSource);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vboxButtons [this.btnMoveSource]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vboxButtons.Gtk.Box+BoxChild
			this.btnCopySource = new global::Gtk.Button ();
			this.btnCopySource.TooltipMarkup = "Copy the source to the target directory location";
			this.btnCopySource.CanFocus = true;
			this.btnCopySource.Name = "btnCopySource";
			this.btnCopySource.UseUnderline = true;
			this.btnCopySource.Label = global::Mono.Unix.Catalog.GetString ("Copy to");
			global::Gtk.Image w20 = new global::Gtk.Image ();
			w20.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-copy", global::Gtk.IconSize.Menu);
			this.btnCopySource.Image = w20;
			this.vboxButtons.Add (this.btnCopySource);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxButtons [this.btnCopySource]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vboxButtons.Gtk.Box+BoxChild
			this.btnCreateSymlink = new global::Gtk.Button ();
			this.btnCreateSymlink.TooltipMarkup = "Create a symbolic link from the source to the target directory";
			this.btnCreateSymlink.CanFocus = true;
			this.btnCreateSymlink.Name = "btnCreateSymlink";
			this.btnCreateSymlink.UseUnderline = true;
			this.btnCreateSymlink.Label = global::Mono.Unix.Catalog.GetString ("Link to");
			global::Gtk.Image w22 = new global::Gtk.Image ();
			w22.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-last", global::Gtk.IconSize.Menu);
			this.btnCreateSymlink.Image = w22;
			this.vboxButtons.Add (this.btnCreateSymlink);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vboxButtons [this.btnCreateSymlink]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vboxButtons.Gtk.Box+BoxChild
			this.btnDoWhole = new global::Gtk.Button ();
			this.btnDoWhole.TooltipMarkup = "Move the source directory to the target location and replace the source by a symbolic link to the newly created target";
			this.btnDoWhole.CanFocus = true;
			this.btnDoWhole.Name = "btnDoWhole";
			this.btnDoWhole.UseUnderline = true;
			this.btnDoWhole.Label = global::Mono.Unix.Catalog.GetString ("Move to and replace with link");
			global::Gtk.Image w24 = new global::Gtk.Image ();
			w24.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-convert", global::Gtk.IconSize.Menu);
			this.btnDoWhole.Image = w24;
			this.vboxButtons.Add (this.btnDoWhole);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vboxButtons [this.btnDoWhole]));
			w25.Position = 3;
			w25.Expand = false;
			w25.Fill = false;
			this.hboxBottom.Add (this.vboxButtons);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hboxBottom [this.vboxButtons]));
			w26.Position = 1;
			// Container child hboxBottom.Gtk.Box+BoxChild
			this.vboxTarget = new global::Gtk.VBox ();
			this.vboxTarget.Name = "vboxTarget";
			this.vboxTarget.Spacing = 6;
			// Container child vboxTarget.Gtk.Box+BoxChild
			this.hboxTargetButtons = new global::Gtk.HBox ();
			this.hboxTargetButtons.Name = "hboxTargetButtons";
			this.hboxTargetButtons.Spacing = 6;
			// Container child hboxTargetButtons.Gtk.Box+BoxChild
			this.btnDeleteTarget = new global::Gtk.Button ();
			this.btnDeleteTarget.TooltipMarkup = "Delete the target directory";
			this.btnDeleteTarget.CanFocus = true;
			this.btnDeleteTarget.Name = "btnDeleteTarget";
			this.btnDeleteTarget.UseStock = true;
			this.btnDeleteTarget.UseUnderline = true;
			this.btnDeleteTarget.Label = "gtk-delete";
			this.hboxTargetButtons.Add (this.btnDeleteTarget);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hboxTargetButtons [this.btnDeleteTarget]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hboxTargetButtons.Gtk.Box+BoxChild
			this.btnOpenTarget = new global::Gtk.Button ();
			this.btnOpenTarget.TooltipMarkup = "Open the target directory with the File Explorer";
			this.btnOpenTarget.CanFocus = true;
			this.btnOpenTarget.Name = "btnOpenTarget";
			this.btnOpenTarget.UseStock = true;
			this.btnOpenTarget.UseUnderline = true;
			this.btnOpenTarget.Label = "gtk-open";
			this.hboxTargetButtons.Add (this.btnOpenTarget);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hboxTargetButtons [this.btnOpenTarget]));
			w28.Position = 1;
			this.vboxTarget.Add (this.hboxTargetButtons);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vboxTarget [this.hboxTargetButtons]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			this.hboxBottom.Add (this.vboxTarget);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hboxBottom [this.vboxTarget]));
			w30.Position = 2;
			this.vboxContent.Add (this.hboxBottom);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vboxContent [this.hboxBottom]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			this.vboxBase.Add (this.vboxContent);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vboxBase [this.vboxContent]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vboxBase.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vboxBase.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vboxBase [this.hseparator1]));
			w33.PackType = ((global::Gtk.PackType)(1));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.Add (this.vboxBase);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 886;
			this.DefaultHeight = 267;
			this.Show ();
		}
	}
}
